Add extra queries and update table
lucabenaventew/vet-clinic-database pull request #2
Opened 2022-10-17 22:58 UTC by lucabenaventew

# Project Updates :green_circle: 
![image](https://user-images.githubusercontent.com/85821183/196296830-4ae032d8-5dd6-47bd-bd5e-e48f07360166.png)
![image](https://user-images.githubusercontent.com/85821183/196298785-d5e57463-3bf4-47ad-942d-1f938e3c3f0e.png)
![image](https://user-images.githubusercontent.com/85821183/196298870-82e83926-e899-4472-875b-146a75770a5d.png)
![image](https://user-images.githubusercontent.com/85821183/196298961-5cf4cfce-8860-4f03-bae2-ec659184cd78.png)

2022-10-17 23:26 UTC, tufoinnkuo10 requested changes
Hi @lucabenaventew 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message


Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-17 23:26 UTC, tufoinnkuo10 commented on queries.sql
> +SELECT COUNT(*) FROM animals;
- [ ] please ensure to add steps when you `UPDATE` the animals' table by setting the species column to unspecified, then roll back the change
- [ ] Also steps when you commit a transaction, delete all records in the animals table, then roll back the transaction

2022-10-18 04:51 UTC, lucabenaventew commented
# Project Updates :green_circle: 
- [ ] Add steps
![image](https://user-images.githubusercontent.com/85821183/196321983-ee68801a-2dbf-4d9e-ad64-d02818e9ac9d.png)
![image](https://user-images.githubusercontent.com/85821183/196322893-57d46a79-d604-44da-87b3-f6edcd1ca5d2.png)
![image](https://user-images.githubusercontent.com/85821183/196323074-db19396e-78ca-4758-8712-89bcfde57a6b.png)
![image](https://user-images.githubusercontent.com/85821183/196324067-21851bbe-7308-4014-a7f4-5f46a22bbd29.png)
![image](https://user-images.githubusercontent.com/85821183/196338365-c0f4635f-058f-4a32-bd64-efc16406da2a.png)

2022-10-18 04:59 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Luca,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾  Congratulations!  🎉💯🌟 

## Highlights 👍
- Database queries properly implemented

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**You can also consider:**
- This project appears to be worked on by a sole contributor, therefore kindly update the Author section of the ReadMe accordingly. 
- MIT license link in your ReadMe is broken, kindly endeavor to fix it.
Implementing the above change(s) will make your ReadMe/ repository stand out even better 😉

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-18 14:00 UTC, merged